app:
name: "bluebell"
mode: "dev"
port: 8080
start_time: 2020-01-01
machine_id: 1

auth:
  jwt_expire: 8760


log:
  level: "debug"
  filename: "bluebell.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "150.158.179.29"
  port: 3307
  user: "root"
  password: "123456"
  db_name: "bluebell"
  max_open_conns: 200
  max_idle_conns: 50

redis:
  host: "150.158.179.29"
  port: 6379
  password: ""
  db: 0
  pool_size: 100